meta_product_name: "Synthshare"
meta_title: "Synthshare: rent local Synths for all your unwanted tasks and chores"
meta_description: "Rent vetted Orange Eye Synths in your area. Cooking, cleaning, advanced theoretical physics - our Synths can do it all."
meta_image: "synthshare.png"                       # should exist in `app/assets/images/`
twitter_account: "@share_synth"   # required for Twitter Cards
